# Generated by Django 4.0.3 on 2023-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0005_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
