# Generated by Django 4.0.3 on 2023-02-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0007_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
